import type { Metadata } from "next";
import { Space_Grotesk  } from "next/font/google";
import "./globals.css";



const grotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-grotesk",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${grotesk.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
